package org.proxectopuding.gui.model.utils;

public enum Notification {

	CHANTER_SELECTED("CHANTER_SELECTED"),
	READING_TONE_SELECTED("READING_TONE_SELECTED"),
	PRECISE_TUNING_NOTE_SELECTED("PRECISE_TUNING_NOTE_SELECTED"),
	PRECISE_TUNING_OCTAVE_SELECTED("PRECISE_TUNING_OCTAVE_SELECTED"),
	FINGERING_NOTE_SELECTED("FINGERING_NOTE_SELECTED"),
	FINGERING_OCTAVE_SELECTED("FINGERING_OCTAVE_SELECTED"),
	FINGERING_NUMBER_SELECTED("FINGERING_NUMBER_SELECTED"),
	FINGERING_NUMBER_ADDED("FINGERING_NUMBER_ADDED"),
	FINGERING_NUMBER_REMOVED("FINGERING_NUMBER_REMOVED");
	
	private String name;
	
	private Notification(String name) {
		this.name = name;
	}
	
	@Override
	public String toString() {
		return this.name;
	}
	
}
